### ISSUE TITLE
Language: Use attributed string to make VoiceOver use the correct voice

### ISSUE THREAD

**Issue by alextrob** [cvs-health/ios-swiftui-accessibility-techniques#12]
Hi!

Thought you'd like to know that it's possible to use  `AttributedString` attributes to tell VoiceOver which language to use with SwiftUI `Text`.

For example:

```swift
Text(
    AttributedString(
        "Bienvenido a nuestra página de inicio.",
        attributes: AttributeContainer().languageIdentifier("es")
    )
)
```

**Comment by pauljadam** [comment]
This is awesome! Thanks for sending me this code! I'm updating the Language technique page now :)

**Comment by pauljadam** [comment]
Xcode project and documentation updated with new technique based on code suggestion.
