### ISSUE TITLE
Error Validation: use .accessibilityValue matching the visible error message text for each invalid input

### ISSUE THREAD

**Issue by MarcSolo** [cvs-health/ios-swiftui-accessibility-techniques#4]
IMO, .accessibilityValue is another valid technique to expose an input's helper text and error message. Unlike .accessibilityHint, I don't think users can disable the announcement of an element's .accessibilityValue. This is why I think using .accessibilityValue may be a more robust approach.

My recommendation is to update the Error Validation coding technique (and associated documentation page) to include a "good" example that demonstrates how to use .accessibilityValue.

**Comment by pauljadam** [comment]
Thanks for the feedback! I've added that second good example using .accessibilityValue. 

Will be out it in the App Store sometime today likely.

**Comment by pauljadam** [comment]
Closing because value property should only be used for the value the user types into the input.
