### ISSUE TITLE
Accordions, HEADING role.

### ISSUE THREAD

**Issue by MayurPatel0** [cvs-health/ios-swiftui-accessibility-techniques#6]
Just like in web we expect accordions to have heading role. For disclosure group, we can achieve this by .accessibilityElement(children: .contain)
and then .accessibilityLabel("The disclosure group text").

This will add the heading role, to the disclosure group.

**Comment by pauljadam** [comment]
@MayurPatel0 I don't think that code actually works, can you build a demo with a VoiceOver screenshot to prove it does?

**Comment by pauljadam** [comment]
Closing until a demo can be provided as I don't think this code works.
